version: '3'

services:

  locust-master:
    build: ./locust-master
    image: locust:01
    container_name: locust-master
    ports:
      - ${LOCUST_WEB_PORT}:8089
      - ${LOCUST_BIND_PORT}:5557
    networks:
      - sac20_net_locust
      
  locust-slave01:
    build: ./locust-slave
    image: locust:02
    container_name: locust-slave01
    networks:
      - sac20_net_locust
    depends_on:
      - "locust-master"

  locust-slave02:
    build: ./locust-slave
    image: locust:02
    container_name: locust-slave02
    networks:
      - sac20_net_locust
    depends_on:
      - "locust-master"

  locust-slave03:
    build: ./locust-slave
    image: locust:02
    container_name: locust-slave03
    networks:
      - sac20_net_locust
    depends_on:
      - "locust-master"

  locust-slave04:
    build: ./locust-slave
    image: locust:02
    container_name: locust-slave04
    networks:
      - sac20_net_locust
    depends_on:
      - "locust-master"

networks:
  sac20_net_locust:
    driver: bridge
